lib/fanta_web/router.ex
defmodule FantaWeb.Router do
  use FantaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phauxth.Authenticate
  end

  scope "/", FantaWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/users", UserController do
      resources "/missions", MissionController do
        get "search", MissionController, :search
        post "search", MissionController, :search
        get "answer_mission", MissionController, :answer_mission
        post "answer_all", MissionController, :answer_all
        get "new_question", MissionController, :new_question
        post "createquestion", MissionController, :createquestion
        get ":question_id/show_question", MissionController, :show_question
        post ":question_id/answer_question", MissionController, :answer_question
        get ":question_id/show_answer", MissionController, :show_answer
      end
    end
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

end

lib/fanta_web/views/layout_view.ex
defmodule FantaWeb.LayoutView do
  use FantaWeb, :view
end

lib/fanta_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Welcome to Phauxth - an extensible authentication library for Elixir web apps</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="<%= page_path @conn, :index %>">Home</a></li>
              <%= if @current_user do %>
              <li><a href="<%= user_path @conn, :index %>">Users</a></li>
              <li><a href="<%= user_mission_path(@conn, :index, @current_user.id) %>">Missions</a></li>
              <li><a href="<%= user_path(@conn, :show, @current_user.id) %>"><%= @current_user.email %></a></li>
              <li><%= link "Logout", to: session_path(@conn, :delete, @current_user), method: :delete %></li>
              <% else %>
              <li><a href="<%= user_path @conn, :new %>">New user</a></li>
              <li><a href="<%= session_path @conn, :new %>">Login</a></li>
              <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>